language: java

install: echo "I trust Maven."

# build, verify, and deploy the snapshot artifacts
script: "mvn deploy --settings maven_deploy_settings.xml"

after_success: mvn cobertura:cobertura coveralls:cobertura

jdk:
  - oraclejdk7
  - oraclejdk8

env:
  global:
    - secure: "TpIrk7R9XBXQXN2KzX/YbbRVEdOmGbWbuLI2XyY89GUWJi3nXMWXZQL2d4eDrPbX3S1pxOXmiQq5m0RG4eoLD9l6LIpn6fEr+jiR8GO4BPjTj0aYk1DFIjFiiDZmPZxGfQlKxCfaObBdfQ8XoTN5j5pCz17xGL0rhDSkIsda9dg="
    - secure: "Xui1LG5gns29jLINZ591LVyNvfpS/hDquHMBmqbz06prD2wxBkrlxSbn3kvo+eJregUgxy6CWI333+FA2AUpMHYfIOwTPjLy3U8WTiuor5oEo9rus7PkIrm0edo1/eC5wIXVxpTz5wI3FO5/2o+vM3lf5PeMDQ71COY57g5M6Ug="
